# 通过自身的entrypoint脚本初始化数据库
FROM mysql:5.7-debian
#设置免密登录
#ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
#将所需文件放到容器中
COPY privileges.sql schema.sql nacos-init.sql /docker-entrypoint-initdb.d/
#设置容器启动时执行的命令
# CMD ["sh", "/mysql/setup.sh"]